<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="10" failed="0" total="12" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite B" duration-ms="269" started-at="2016-01-03T07:07:36Z" finished-at="2016-01-03T07:07:36Z">
    <groups>
    </groups>
    <test name="Test 1" duration-ms="130" started-at="2016-01-03T07:07:36Z" finished-at="2016-01-03T07:07:36Z">
      <class name="dataDrivenFramework.suiteB.Test1">
        <test-method status="SKIP" signature="test1(java.util.HashMap)[pri:0, instance:dataDrivenFramework.suiteB.Test1@66d2e7d9]" name="test1" duration-ms="25" started-at="2016-01-03T12:37:36Z" data-provider="suiteBDataProvider" finished-at="2016-01-03T12:37:36Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Col1=C11, Col2=C22, Col3=C33, Runmode=Y, Result=}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test Test1 inside the suite SuiteB. Reason: Suite NOT runnable.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test Test1 inside the suite SuiteB. Reason: Suite NOT runnable.
	at dataDrivenFramework.dataDriven.TestBase.validateRunmodes(TestBase.java:27)
	at dataDrivenFramework.suiteB.Test1.test1(Test1.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1220)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="SKIP" signature="test1(java.util.HashMap)[pri:0, instance:dataDrivenFramework.suiteB.Test1@66d2e7d9]" name="test1" duration-ms="24" started-at="2016-01-03T12:37:36Z" data-provider="suiteBDataProvider" finished-at="2016-01-03T12:37:36Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Col1=C21, Col2=C23, Col3=C34, Runmode=N, Result=}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test Test1 inside the suite SuiteB. Reason: Suite NOT runnable.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test Test1 inside the suite SuiteB. Reason: Suite NOT runnable.
	at dataDrivenFramework.dataDriven.TestBase.validateRunmodes(TestBase.java:27)
	at dataDrivenFramework.suiteB.Test1.test1(Test1.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1220)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="SKIP" signature="test1(java.util.HashMap)[pri:0, instance:dataDrivenFramework.suiteB.Test1@66d2e7d9]" name="test1" duration-ms="36" started-at="2016-01-03T12:37:36Z" data-provider="suiteBDataProvider" finished-at="2016-01-03T12:37:36Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Col1=C31, Col2=C24, Col3=C35, Runmode=Y, Result=}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test Test1 inside the suite SuiteB. Reason: Suite NOT runnable.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test Test1 inside the suite SuiteB. Reason: Suite NOT runnable.
	at dataDrivenFramework.dataDriven.TestBase.validateRunmodes(TestBase.java:27)
	at dataDrivenFramework.suiteB.Test1.test1(Test1.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1220)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
      </class> <!-- dataDrivenFramework.suiteB.Test1 -->
    </test> <!-- Test 1 -->
    <test name="Test 2" duration-ms="127" started-at="2016-01-03T07:07:36Z" finished-at="2016-01-03T07:07:36Z">
      <class name="dataDrivenFramework.suiteB.Test2">
        <test-method status="SKIP" signature="test2(java.util.HashMap)[pri:0, instance:dataDrivenFramework.suiteB.Test2@5ae9a829]" name="test2" duration-ms="23" started-at="2016-01-03T12:37:36Z" data-provider="suiteBDataProvider" finished-at="2016-01-03T12:37:36Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Col1=C11, Col2=C22, Col3=C33, Col4=C43, Runmode=Y, Result=}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test Test2 inside the suite SuiteB. Reason: Suite NOT runnable.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test Test2 inside the suite SuiteB. Reason: Suite NOT runnable.
	at dataDrivenFramework.dataDriven.TestBase.validateRunmodes(TestBase.java:27)
	at dataDrivenFramework.suiteB.Test2.test2(Test2.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1220)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="SKIP" signature="test2(java.util.HashMap)[pri:0, instance:dataDrivenFramework.suiteB.Test2@5ae9a829]" name="test2" duration-ms="40" started-at="2016-01-03T12:37:36Z" data-provider="suiteBDataProvider" finished-at="2016-01-03T12:37:36Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Col1=C21, Col2=C23, Col3=C34, Col4=C45, Runmode=N, Result=}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test Test2 inside the suite SuiteB. Reason: Suite NOT runnable.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test Test2 inside the suite SuiteB. Reason: Suite NOT runnable.
	at dataDrivenFramework.dataDriven.TestBase.validateRunmodes(TestBase.java:27)
	at dataDrivenFramework.suiteB.Test2.test2(Test2.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1220)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="SKIP" signature="test2(java.util.HashMap)[pri:0, instance:dataDrivenFramework.suiteB.Test2@5ae9a829]" name="test2" duration-ms="22" started-at="2016-01-03T12:37:36Z" data-provider="suiteBDataProvider" finished-at="2016-01-03T12:37:36Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Col1=C31, Col2=C24, Col3=C35, Col4=C46, Runmode=Y, Result=}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test Test2 inside the suite SuiteB. Reason: Suite NOT runnable.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test Test2 inside the suite SuiteB. Reason: Suite NOT runnable.
	at dataDrivenFramework.dataDriven.TestBase.validateRunmodes(TestBase.java:27)
	at dataDrivenFramework.suiteB.Test2.test2(Test2.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1220)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
      </class> <!-- dataDrivenFramework.suiteB.Test2 -->
    </test> <!-- Test 2 -->
  </suite> <!-- Suite B -->
  <suite name="Suite A" duration-ms="1623" started-at="2016-01-03T07:07:34Z" finished-at="2016-01-03T07:07:35Z">
    <groups>
    </groups>
    <test name="Test 1" duration-ms="1262" started-at="2016-01-03T07:07:34Z" finished-at="2016-01-03T07:07:35Z">
      <class name="dataDrivenFramework.suiteA.Test1">
        <test-method status="PASS" signature="test1(java.util.HashMap)[pri:0, instance:dataDrivenFramework.suiteA.Test1@1936f0f5]" name="test1" duration-ms="99" started-at="2016-01-03T12:37:35Z" data-provider="suiteADataProvider" finished-at="2016-01-03T12:37:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Col1=C11, Col2=C22, Col3=C33, Runmode=Y, Result=}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="SKIP" signature="test1(java.util.HashMap)[pri:0, instance:dataDrivenFramework.suiteA.Test1@1936f0f5]" name="test1" duration-ms="82" started-at="2016-01-03T12:37:35Z" data-provider="suiteADataProvider" finished-at="2016-01-03T12:37:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Col1=C21, Col2=C23, Col3=C34, Runmode=N, Result=}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test Test1inside the suite SuiteA. Reason: Test input NOT runnable.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test Test1inside the suite SuiteA. Reason: Test input NOT runnable.
	at dataDrivenFramework.dataDriven.TestBase.validateRunmodes(TestBase.java:43)
	at dataDrivenFramework.suiteA.Test1.test1(Test1.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1220)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="PASS" signature="test1(java.util.HashMap)[pri:0, instance:dataDrivenFramework.suiteA.Test1@1936f0f5]" name="test1" duration-ms="88" started-at="2016-01-03T12:37:35Z" data-provider="suiteADataProvider" finished-at="2016-01-03T12:37:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Col1=C31, Col2=C24, Col3=C35, Runmode=Y, Result=}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
      </class> <!-- dataDrivenFramework.suiteA.Test1 -->
    </test> <!-- Test 1 -->
    <test name="Test 2" duration-ms="329" started-at="2016-01-03T07:07:35Z" finished-at="2016-01-03T07:07:35Z">
      <class name="dataDrivenFramework.suiteA.Test2">
        <test-method status="SKIP" signature="test2(java.util.HashMap)[pri:0, instance:dataDrivenFramework.suiteA.Test2@2669b199]" name="test2" duration-ms="78" started-at="2016-01-03T12:37:35Z" data-provider="suiteADataProvider" finished-at="2016-01-03T12:37:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Col1=C11, Col2=C22, Col3=C33, Col4=C43, Runmode=Y, Result=}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test Test2 inside the suite SuiteA. Reason: Test case NOT runnable.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test Test2 inside the suite SuiteA. Reason: Test case NOT runnable.
	at dataDrivenFramework.dataDriven.TestBase.validateRunmodes(TestBase.java:37)
	at dataDrivenFramework.suiteA.Test2.test2(Test2.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1220)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="SKIP" signature="test2(java.util.HashMap)[pri:0, instance:dataDrivenFramework.suiteA.Test2@2669b199]" name="test2" duration-ms="83" started-at="2016-01-03T12:37:35Z" data-provider="suiteADataProvider" finished-at="2016-01-03T12:37:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Col1=C21, Col2=C23, Col3=C34, Col4=C45, Runmode=N, Result=}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test Test2 inside the suite SuiteA. Reason: Test case NOT runnable.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test Test2 inside the suite SuiteA. Reason: Test case NOT runnable.
	at dataDrivenFramework.dataDriven.TestBase.validateRunmodes(TestBase.java:37)
	at dataDrivenFramework.suiteA.Test2.test2(Test2.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1220)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="SKIP" signature="test2(java.util.HashMap)[pri:0, instance:dataDrivenFramework.suiteA.Test2@2669b199]" name="test2" duration-ms="109" started-at="2016-01-03T12:37:35Z" data-provider="suiteADataProvider" finished-at="2016-01-03T12:37:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Col1=C31, Col2=C24, Col3=C35, Col4=C46, Runmode=Y, Result=}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test Test2 inside the suite SuiteA. Reason: Test case NOT runnable.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test Test2 inside the suite SuiteA. Reason: Test case NOT runnable.
	at dataDrivenFramework.dataDriven.TestBase.validateRunmodes(TestBase.java:37)
	at dataDrivenFramework.suiteA.Test2.test2(Test2.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1220)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
      </class> <!-- dataDrivenFramework.suiteA.Test2 -->
    </test> <!-- Test 2 -->
  </suite> <!-- Suite A -->
  <suite name="My Project" duration-ms="0" started-at="2016-01-03T07:07:36Z" finished-at="2016-01-03T07:07:36Z">
    <groups>
    </groups>
  </suite> <!-- My Project -->
</testng-results>
